### ISSUE TITLE
`easing` works not as expected

### ISSUE THREAD

**Issue by shunia** [Stanko/react-animate-height#39]
When comes to animation, it's hard to describe what's happening I think, so I recorded a gif:

![animation_problem](https://user-images.githubusercontent.com/779430/35964652-4f28806e-0cf3-11e8-92eb-966d78450488.gif)

I have a container component contains children list to collapse, it's the show/hide part inside the gif above, codes structure like here:
```typescript
// container.ts
<div>
    <AnimateHeight height={this.state.collapsed ? 'auto' : 0} duration={500} easing='linear'>
        {this.props.children}
    </AnimateHeight>
</div>

// sortby.ts
<Container>
    <div className='sort-list'>
        {/* contents here */}
    </div>
<Container/>

// species.ts
<Container>
    <div className='species-list'>
        {/* contents here */}
    </div>
<Container/>
```

My guess is `AnimateHeight`'s calculating by the first child's(`sortby`) height, so caused the crappy transition for the second child(`species`), but this is just a wild guess.

**Comment by Stanko** [comment]
Hello @shunia,

This is actually expected behaviour, and it has nothing to do with easing. To work correctly content needs to be rendered **before** height is changed to `auto`. 

You are adding list content at the same time you are changing the height to `auto`, and `AnimateHeight` is using height of "All" row which seems to be rendered already.

Check the example here:

https://codesandbox.io/s/vjzy07p4x5

Hope that helps, cheers!

**Comment by shunia** [comment]
Yes, `AnimateHeight` works right. And the way I use it too.
The problem is my css-style applied to `species-list`.

Thank you for your quick reply!

**Comment by Stanko** [comment]
No worries, glad it helped! 🎉
