### ISSUE TITLE
[Question] Vue.js equivalent

### ISSUE THREAD

**Issue by iAlirezaKML** [Stanko/react-animate-height#41]
Hello @Stanko,
Is there any Vue.js equivalent?
I've tried both [`vue-smooth-height`](https://www.npmjs.com/package/vue-smooth-height) and [`vue-height-tween-transition`](https://github.com/BKWLD/vue-height-tween-transition) but since I'm using my own custom transitions, these solutions don't meet my requirements.

**Comment by Stanko** [comment]
Hey @iAlirezaKML,
Unfortunately I'm not familiar with Vue, so I can't really help. But feel free to port it.
Cheers!

**Comment by leonzalion** [comment]
I'm 4 years late, but in case anybody is interested, I've created a Vue version that is pretty much a 1-to-1 port of React Animate Height since I couldn't find any existing alternatives which support Vue 3: https://github.com/leonzalion/vue-animate-height

Thanks @Stanko for creating this amazing package :)
