### ISSUE TITLE
Remove overflow:hidden when animation completed

### ISSUE THREAD

**Issue by NikolayYakovenko** [Stanko/react-animate-height#57]
Remove `overflow: hidden` when animation completed.
Here is a problem with `overflow: hidden`.
When the collapsible container has dropdowns or tooltips, the part of their content can be truncated by the parent.

The result I would expect is similar to the behavior when we set  `height='auto'`, and in the end, the parent won't have `overflow: hidden`.

**Comment by Stanko** [comment]
Hello @NikolayYakovenko,
`overflow: hidden` is removed when animation is complete and `height = auto`. 

https://github.com/Stanko/react-animate-height/blob/master/source/AnimateHeight.js#L143-L147

If height is set to a specific value `overflow: hidden` needs to be applied as content needs to be clipped.

Cheers!

**Comment by brewern** [comment]
@NikolayYakovenko I ran into the same need, it seems since my height is a specific number overflow hidden is never removed. Since there are no open and closed classes, I used onAnimationEnd to check if my height state was greater than zero, and then set the state of the height to auto. Seems to work for my use-case.

`onAnimationEnd = () => {
    const dHeight = this.state.dropdownHeight;
    if (typeof dHeight === 'number' && dHeight > 0) {
      this.setState({ dropdownHeight: "auto" });
    }
  }`

Note: I'm checking if the type is a number to suppress a Flow error on dHeight in my own component.
