### ISSUE TITLE
Animation doesn't work on absolute positioned elements

### ISSUE THREAD

**Issue by WebDeg-Brian** [Stanko/react-animate-height#60]
React-animate-height doesn't seem to work on absolute positioned element. I'm not sure whether it's an issue or an expected behavior.  
This is quite self-explanatory so I don't think people would need a code example.

**Comment by Stanko** [comment]
Hello @WebDeg-Brian,
Unfortunately absolute positioned elements are "outside of the flow", and they are not expanding parent which is used for measuring. What you should do is to apply `position: absolute` on animate height directly instead of content.

Here is working example:
https://codesandbox.io/s/l41z840r17

Cheers!

**Comment by WebDeg-Brian** [comment]
Thanks for looking into this! I'll definitely apply this to my dropdown component!
