### ISSUE TITLE
Low FPS on Firefox

### ISSUE THREAD

**Issue by sunglux** [Stanko/react-animate-height#65]
On Firefox 64.0 on Ubuntu 18.04, animation for growing a height has significantly lower fps than in Chrome.

**Code example**
At this time I do not have the resources to construct a working reproduction demo

**Expected behavior**
FPS is not low

**Possible Solution**
Not sure.

**Steps to Reproduce (for bugs)**
Not a bug

**Screenshots**
**Chrome**
![2019-01-16_16 07 39](https://user-images.githubusercontent.com/31295444/51227781-f0b3e680-19a9-11e9-9beb-45ebc2e7295e.png)

**Firefox**
![2019-01-16_16 10 23](https://user-images.githubusercontent.com/31295444/51227782-f27daa00-19a9-11e9-9128-dbd2935c0f91.png)

**Your Environment**
 - Version used: 2.0.6
 - OS: Ubuntu 18.04
 - Browser: Firefox
 - Version: 64.0

**Additional context**
Just had a glimpse of the code, and if I understand right, this library animates the height by repeatedly calling `setState`. What is the performance implication vs. using css animation which can be GPU accelerated?

**Comment by Stanko** [comment]
Hello @sunglux,
It is true that library is calling `setState` multiple times, but it is three the most. That shouldn't be issue. Only non-performant thing library does, is that it is changing and transitioning `height` css property (instead of `scale`). Unfortunately this is the only way to do it.

I've just tried Firefox on mac, and it works smoothly. So this might be the issue related to ubuntu/video driver/firefox combination. I've seen similar reports on other libraries.

If there is something I can implement, I would gladly do it. But unfortunately, I have no real clue if the library is the problem.

Cheers!

**Comment by sunglux** [comment]
Thanks for your clarification despite not having the reproduction of issue. Closing
