### ISSUE TITLE
Animation breaking behavior of inner elements

### ISSUE THREAD

**Issue by oyeanuj** [Stanko/react-animate-height#94]
Hi @Stanko, thank you for creating this wonderful library! I'm running into this issue where on adding this library, I'm noticing a couple of issues with its children:

1. TextArea `autoFocus` is not working anymore.
2. Width of the children is animating as well.

**Code example**
```jsx
<AnimateHeight duration = { 500 } height = { showResponses ? "auto" : 0 }> {/* this and it's child: width: 100% */}
  { showResponses && <ResponsesTextArea autoFocus { ...props } /> } {/* this and it's child: width: 100% */}
</AnimateHeight>
```

```css
.rah-static {
  width:  100%;

  & > div {
    width: 100%;
  }
}
```

**Expected behavior**
I'd expect the height to animate vertically but it not affect the width or the affect the autofocus.

**Steps to Reproduce (for bugs)**

Code above

**Screenshots**

![Screen Recording 2020-07-22 at 8 36 21 AM](https://user-images.githubusercontent.com/9633371/88197490-6c25d200-cbf7-11ea-904f-210d8d7ef69b.gif)

**Your Environment**
 - Version used: Latest
 - OS: Mac OS 10.15.4
 - Browser  Chrome
 - Version 85

**Additional context**

I'm trying to animate the new section opening up on click, and for the text area to be focused when it opens up.

Thank you!

**Comment by Stanko** [comment]
Hello @oyeanuj,

Auto focus, I think that is the intended behaviour. It doesn't work as textarea is already rendered (but hidden with `display: none`) and auto focus is not triggered when the content is shown.

You can easily focus it using `onAnimationEnd` callback:

```jsx
  handleAnimationEnd = newHeight => {
    if (newHeight !== 0) {
      this.textarea.focus();
    }
  };

  // ...

  <AnimateHeight onAnimationEnd={this.handleAnimationEnd}>
```

As for the width issue, I don't think that is the issue with the library. Library doesn't fiddle with `width` at all. As you will see in the example below, textarea works just fine with the library. 

It might be that your CSS layout is the problem - maybe a flex container issue?


I created a small example for both things here:
https://codesandbox.io/s/react-animate-height-basic-example-zsmjv?file=/src/index.js

Hope this helps a little!
Cheers!

P.S. I don't recommend altering styles of the inside div (that's why it doesn't have a class) as it can easily mess up with the library's calculations.
